Feature-biryuchkov-task-1
sadads1337/fit-gl pull request #13
Opened 2021-02-26 14:10 UTC by biryuc

2021-02-27 12:30 UTC, sadads1337 requested changes

2021-02-27 12:30 UTC, sadads1337 commented on src/task1/CubeWindow.cpp
> +        glVertexAttribPointer(colAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(VertexData), reinterpret_cast<char *>(sizeof(QVector3D) ));
```reinterpret_cast<char *>(sizeof(QVector3D) )``` А зачем это? Можете объяснить?

2021-02-27 12:30 UTC, sadads1337 commented on src/task1/CubeWindow.cpp
> +        glGenBuffers(1, &v_ibo);
В таком подходе вы копируете в видеопамять на каждой отрисовке. Точно ли это то, чего вы хотите?

2021-02-27 12:30 UTC, sadads1337 commented on src/task1/CubeWindow.cpp
> +            QColor color = QColorDialog::getColor();
```suggestion
            const auto color = QColorDialog::getColor();

```

2021-02-27 12:30 UTC, sadads1337 commented on src/task1/CubeWindow.cpp
> +        QVector2D diff = QVector2D(e->localPos()) - mousePressPosition;
```suggestion
        const autodiff = QVector2D(e->localPos()) - mousePressPosition;

```
и ниже тоже

https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

2021-02-27 12:30 UTC, sadads1337 commented on src/task1/CubeWindow.hpp
> +        QVector2D mousePressPosition;
Давайте зададим осмысленные значения по-умолчанию

2021-02-27 12:30 UTC, sadads1337 commented on src/task1/Shaders/square.fs
> +        uniform vec4 col = vec4(1.0, 0.0, 0.0, 1.0);
Давайте отформатируем шейдер, чтобы было "удобнее читать ваш код". И второй шейдер тоже

2021-02-27 12:30 UTC, sadads1337 commented
Зачем вы удаляете папку `Lesson1`? Это лишнее изменение.

2021-02-28 04:38 UTC, biryuc commented on src/task1/CubeWindow.cpp
> +        glVertexAttribPointer(colAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(VertexData), reinterpret_cast<char *>(sizeof(QVector3D) ));
Вообще я взял этот пример в интернете(при замене на VertexData gvertices[]) и там было сказано :Позволяет преобразовывать любой указатель в указатель любого другого типа. Также позволяет преобразовывать любой целочисленный тип в любой тип указателя и наоборот.

2021-02-28 04:53 UTC, sadads1337 commented on src/task1/CubeWindow.cpp
> +        glVertexAttribPointer(colAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(VertexData), reinterpret_cast<char *>(sizeof(QVector3D) ));
Давайте подумаем:

- `sizeof(QVector3D)` - возвращает вам размер в байтах, структуры `QVector3D`
- Далее вы конвертируете ее в указатель на `char` с помощью `reinterpret_cast<char *>(...)`

Подумайте получите ли вы валидный адрес? Если да, то что это за адрес?
Посмотрите на сигнатуру функции `glVertexAttribPointer`, не к `void*` ли вам нужно привести ваши типы?

2021-02-28 06:08 UTC, biryuc commented on src/task1/CubeWindow.cpp
> +        glVertexAttribPointer(colAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(VertexData), reinterpret_cast<char *>(sizeof(QVector3D) ));
Да , согласен, изменил

2021-02-28 06:08 UTC, biryuc commented on src/task1/CubeWindow.hpp
> +        QVector2D mousePressPosition;
Можете подсказать как это сделать, есть специальные значения для QVector4D? Просто в документации не нашел

2021-02-28 06:08 UTC, biryuc commented on src/task1/CubeWindow.cpp
> +        glGenBuffers(1, &v_ibo);
Нет конечно, но не понимаю как сделать по другому . Вот отсюда брал этот пример: https://ravesli.com/urok-4-risuem-nash-pervyj-treugolnik-v-opengl/

2021-03-04 07:13 UTC, sadads1337 commented
@biryuc все еще модифицируете код примера из 1-го урока

2021-03-04 07:17 UTC, sadads1337 requested changes

2021-03-04 07:17 UTC, sadads1337 commented on src/task1/CubeWindow.cpp
> +        glGenBuffers(1, &vbo);
А удалять буферы кто будет? Нужно либо написать деструктор, либо использовать Qt обертки

2021-03-08 05:47 UTC, closed without merging