First task
sadads1337/fit-gl pull request #15
Opened 2021-02-28 06:04 UTC by nickshabalov

The first task with two cubes with the ability to choose a color and set the axes of rotation.

2021-02-28 07:27 UTC, sadads1337 requested changes

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.17)
Тут практически все лишнее, оно и так есть в корневом cmake

Должно остаться только `add_executable`, `target_link_libraries`

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/CMakeLists.txt
> +add_executable(${PROJECT_NAME} glad.c main.cpp Widget.cpp Widget.h Object3D.cpp Object3D.h Window.cpp Window.h MainWindow.cpp MainWindow.h)
Зачем вам `glad.c` ?

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} ${REQUIRED_LIBS_QUALIFIED} GL GLU glfw3 X11 Xxf86vm Xrandr pthread Xi dl Xinerama Xcursor assimp)
Зачем вам все эти зависимости?

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/MainWindow.cpp
> +    QMenuBar *menuBar = new QMenuBar;
Зачем вам указатели?

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/MainWindow.cpp
> +    QMenuBar *menuBar = new QMenuBar;
Вы сможете объяснить почему вам код валиден и работает? И в нем не будет утечек памяти?)

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/MainWindow.cpp
> +    connect(addNew, &QAction::triggered, this, &MainWindow::onAddNew);
Зачем вам `slot` `addNew` ?

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Object3D.h
> +    VertexData()
Почему не `= default()` ? И вообще какой смысл несет неинициализированная структура?

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Object3D.h
> +    QOpenGLTexture *m_texture;
Сырой указатель, да еще и с утечкой. Почему не `unique_ptr`?

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Object3D.cpp
> +    if(m_vertexBuffer.isCreated())
Деструктор не нужен, если бы вы использовали умные указатели.

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Object3D.cpp
> +    int offset = 0;
```suggestion
    auto offset = 0;
```

и ниже по коду, следуйте правилу `AAA` - almost always auto 

https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Object3D.cpp
> +Object3D::Object3D():
В чем смысл такого "пустого" объекта ?

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Widget.cpp
> +    m_objects.append(new Object3D(vertexes, indexes, QImage("/home/nikita/CLionProjects/Task-1/cube.jpg")));
Тут утечка будет, кто за вас позовет `delete`?
Используйте `shared_ptr` или `unique_ptr`

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Widget.cpp
> +    m_objects.append(new Object3D(vertexes, indexes, QImage("/home/nikita/CLionProjects/Task-1/cube.jpg")));
Не нужно хардкодить пути, вы сломаете сборку всем остальным. Добавьте ваши текстуру в ресурсы (по аналогии с шейдерами в примере с треугольником).

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Widget.cpp
> +    QVector<VertexData> vertexes;
```
 QVector<VertexData> vertexes{
    VertexData{ {-half_width, half_width, half_width}, {0.0, 1.0}, {0.0, 0.0, 1.0} },
    ...
};
```

можно так, и будет "меньше букоф"

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Widget.cpp
> +    if(event->buttons() == Qt::LeftButton){
Если это не "интересующее вас событие", то вы должны передать его родительскому обработчику, а не просто делать `accept`

```
void Widget::mousePressEvent(QMouseEvent *event) {
    if(event->buttons() == Qt::LeftButton){
         // do something
        event.accept();
    }
    // Move to parent
    QWidget::mousePressEvent(event);
}
```

И в остальных функциях тоже

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Window.h
> +    Widget *widget;
Опять держите "сырые" указатели

2021-02-28 07:27 UTC, sadads1337 commented on src/Shabalov/Task-1/Widget.cpp
> +    if(!m_program.addShaderFromSourceFile(QOpenGLShader::Vertex, "/home/nikita/CLionProjects/Task-1/vshader.vsh"))
Добавьте шейдеры в ресурсы

2021-02-28 07:28 UTC, sadads1337 commented
Давайте поправим эти замечания, а с остальными разберем на паре.

2021-03-01 09:33 UTC, nickshabalov commented
Всё поправил!

2021-03-04 07:37 UTC, sadads1337 requested changes

2021-03-04 07:37 UTC, sadads1337 commented on src/Shabalov/Task-1/Window.h
> +    Widget *widget;
Не поправлено

2021-03-04 07:37 UTC, sadads1337 commented on src/Shabalov/Task-1/Window.cpp
> +    auto *slider = new QSlider(Qt::Vertical);
unique_ptr

2021-03-04 07:37 UTC, sadads1337 commented on src/Shabalov/Task-1/Window.cpp
> +    widget = new Widget;
А где же ваш delete?

2021-03-04 07:37 UTC, sadads1337 commented on src/Shabalov/Task-1/Widget.h
> +    Widget(QWidget *parent = nullptr);
```suggestion
    explicit Widget(QWidget *parent = nullptr);
```

2021-03-04 07:37 UTC, sadads1337 commented on src/Shabalov/Task-1/Widget.h
> +    ~Widget();
```suggestion
    ~Widget() override;
```

2021-03-04 07:37 UTC, sadads1337 commented
Нужно поправить компиляцию

2021-03-05 05:26 UTC, nickshabalov commented
Всё поправил

2021-03-05 10:53 UTC, sadads1337 commented
Вы не правильно использовали `std::unique_ptr`, это приводило к `double delete`. -> Утечкам памяти на выходе из приложения.

- Либо вы используете сырые указатели обернутые в аналог `gsl::owner` (поправил сам)
- Либо используете `std::unique_ptr` с пустым `deleter`

2021-03-05 11:20 UTC, sadads1337 approved these changes

2021-03-05 11:20 UTC, merged