Moseykov Ignaty 17352 Full first task
sadads1337/fit-gl pull request #17
Opened 2021-03-01 06:42 UTC by MoseykovIgnat

2021-03-03 02:28 UTC, sadads1337 commented
Поправьте ошибки компиляции

2021-03-03 02:49 UTC, MoseykovIgnat commented
Исправил..)

2021-03-04 07:43 UTC, sadads1337 requested changes

2021-03-04 07:43 UTC, sadads1337 commented on src/Moseykov/task1/CMakeLists.txt
> +add_executable(task1 ${TASK1_SRCS})
Давайте назовем `target`, каким-нибудь уникальным именем. Например, `MoseykovTask1`

2021-03-04 07:43 UTC, sadads1337 commented on src/Moseykov/task1/SquareWindow.cpp
> +//struct VertexData {
Закомментированный код нужно удалить

2021-03-04 07:43 UTC, sadads1337 commented on src/Moseykov/task1/SquareWindow.cpp
> +  glVertexAttribPointer(posAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(QVector3D), 0);
Вам везет, что без `bind()` на буферы перед отрисовкой все работает. Почитайте документацию, состояние буфера после отрисовки не гарантируется, пока не будет вызван `bind()`

2021-03-04 07:43 UTC, sadads1337 commented on src/Moseykov/task1/SquareWindow.hpp
> +  void keyPressEvent(QKeyEvent *event) override;
Почему выше `e`, а тут `event` ?)))))

2021-03-05 05:22 UTC, MoseykovIgnat commented on src/Moseykov/task1/CMakeLists.txt
> +add_executable(task1 ${TASK1_SRCS})
Сделано)

2021-03-05 05:23 UTC, MoseykovIgnat commented on src/Moseykov/task1/SquareWindow.cpp
> +//struct VertexData {
Сделано

2021-03-05 05:23 UTC, MoseykovIgnat commented on src/Moseykov/task1/SquareWindow.cpp
> +  glVertexAttribPointer(posAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(QVector3D), 0);
Сделано

2021-03-05 05:23 UTC, MoseykovIgnat commented on src/Moseykov/task1/SquareWindow.hpp
> +  void keyPressEvent(QKeyEvent *event) override;
Ахаха, это все с разных сайтов..) Исправил))

2021-03-05 11:31 UTC, sadads1337 approved these changes

2021-03-05 11:31 UTC, sadads1337 commented on src/Moseykov/task1/SquareWindow.cpp
> +  glVertexAttribPointer(posAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(QVector3D), 0);
Лишний вызов `allocate`, я поправил

2021-03-05 11:38 UTC, merged