Bondarchuk Task1
sadads1337/fit-gl pull request #19
Opened 2021-03-01 08:13 UTC by wbondarchuk

2021-03-04 07:51 UTC, sadads1337 requested changes

2021-03-04 07:51 UTC, sadads1337 commented on src/Bondarchuk/Task1/CubeWindow.cpp
> +/*0, 1, 2, 3, 3, 1, 1, 4, 3, 5, 5, 4, 4, 6, 5, 7, 7, 6, 6, 0, 7, 2, 2, 0*/
Это индексы ребер?

2021-03-04 07:51 UTC, sadads1337 commented on src/Bondarchuk/Task1/CubeWindow.cpp
> +  glGenBuffers(1, &ibo);
Где ваш delete для буфера?

2021-03-04 07:51 UTC, sadads1337 commented on src/Bondarchuk/Task1/CubeWindow.cpp
> +  glBufferData(GL_ELEMENT_ARRAY_BUFFER, 34 * sizeof(unsigned int), indexes.data(), GL_STATIC_DRAW);
Каждый кадр вы копируете значения буфера.

1. Нужно сохранить `vbo, ibo` в поля класса.
2. Позвать `glGenBuffers`, `glBindBuffer`, `glBufferData` в методе `init()`
3. А перед отрисовкой делать только `glBindBuffer`

2021-03-04 07:51 UTC, sadads1337 commented on src/Bondarchuk/Task1/CubeWindow.cpp
> +  glVertexAttribPointer(posAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(QVector3D), 0);
А почему не `program_->setAttributeBuffer()`

2021-03-04 07:52 UTC, sadads1337 requested changes

2021-03-04 07:52 UTC, sadads1337 commented on src/Bondarchuk/Task1/CMakeLists.txt
> +add_executable(lesson1 ${LESSON1_SRCS})
Давайте дадим уникальное название для `target`, например, `BondarchukTask1`

2021-03-06 13:08 UTC, wbondarchuk commented on src/Bondarchuk/Task1/CubeWindow.cpp
> +/*0, 1, 2, 3, 3, 1, 1, 4, 3, 5, 5, 4, 4, 6, 5, 7, 7, 6, 6, 0, 7, 2, 2, 0*/
Это индексы для отрисовки ребер. Завел для них отдельный массив 
constexpr std::array<GLuint, 24u> lineindexes = { 0, 1, 2, 3, 3, 1, 1, 4, 3, 5, 5, 4, 4, 6, 5, 7, 7, 6, 6, 0, 7, 2, 2, 0};

2021-03-06 13:53 UTC, wbondarchuk commented on src/Bondarchuk/Task1/CMakeLists.txt
> +add_executable(lesson1 ${LESSON1_SRCS})
А как это сделать?

2021-03-06 14:03 UTC, wbondarchuk commented on src/Bondarchuk/Task1/CMakeLists.txt
> +add_executable(lesson1 ${LESSON1_SRCS})
разобрался
правда сначала всё сломал)

2021-03-06 16:08 UTC, wbondarchuk commented
![Снимок экрана (323)](https://user-images.githubusercontent.com/55180931/110213012-c5b1e700-7ed0-11eb-9df8-9b4df9274fd6.png)
Из-за чего такая ошибка может выходить?

2021-03-09 08:40 UTC, sadads1337 approved these changes

2021-03-09 08:40 UTC, sadads1337 commented on src/Bondarchuk/Task1/CubeWindow.cpp
> +constexpr std::array<GLuint, 24u> lineindexes = {
Тут будет warning: `unused variable` :)

2021-04-01 10:32 UTC, merged