Task2
sadads1337/fit-gl pull request #25
Opened 2021-03-05 14:49 UTC by biryuc

2021-03-20 18:57 UTC, sadads1337 requested changes
Общие впечатления - сильно переусложненный код

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/CMakeLists.txt
> +add_subdirectory(Problem_2)
давайте как-то единообразно именовать и назовем`Task2` :)

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/CMakeLists.txt
> +find_package(OpenGL REQUIRED)
А зачем эта зависимость? Qt за вас это сделает

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/CMakeLists.txt
> +qt5_wrap_ui(UI_HEADERS mainwindow.ui)
Лишнее, если вы запускаете cmake из корня проекта `fit-gl`, то все заработает автоматически

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cubewidget.cpp
> +/****************************************************************************
Жестко :) Думаю, мы не нарушаем лицензию и можем в учебных целях не тащить `copyrights`

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cubewidget.cpp
> +void CubeWidget::setFaceMode()
Почему бы не сделать одну функцию `setMode(...)`, которая параметризуется `colorMode`

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cubewidget.cpp
> +    pCube_.reset(
Признак плохого кода, написание `new`, в данном случае ничего не случится. Но если гипотетически ваш конструктор `Cube` выкинет исключение, мы упадем и память утечет.

Давайте через `operator=` сделаем атомарную замену

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cubewidget.cpp
> +void CubeWidget::makeNewGrid(int grid_steps)
```suggestion
void CubeWidget::makeNewGrid(const int grid_steps)
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cubewidget.cpp
> +void CubeWidget::resizeGL(int w, int h)
```suggestion
void CubeWidget::resizeGL(const int w, const int h)
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/ui_mainwindow.h
> +/********************************************************************************
Лишний файл, который сгенерируется при сборке. Не нужно его заливать в PR

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/rectflatgridsurface.hpp
> +class rectFlatGridSurface final : public GLObject, protected QOpenGLFunctions
Не очень хорошо, что у вас несколько точек входа в `OpenGL`. Почему бы объекту не принимать интерфейс `QOpenGLFunction` в методе `draw`?

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/rectflatgridsurface.cpp
> +{
Лишняя функция, за вас все сделает деструктор объекты VBO и IBO

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/rectflatgridsurface.cpp
> +rectFlatGridSurface::~rectFlatGridSurface()
Имплементация по умолчанию сделает все за вас

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/mainwindow.cpp
> +void MainWindow::on_faceNumSpinbox_valueChanged(int arg1)
```suggestion
void MainWindow::on_faceNumSpinbox_valueChanged(const int arg1)
```
+ давайте дадим осмысленное имя

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/mainwindow.cpp
> +void MainWindow::on_morphFactorSlider_valueChanged(int value)
```suggestion
void MainWindow::on_morphFactorSlider_valueChanged(const int value)
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/mainwindow.cpp
> +    double factor = static_cast<float>(value) / (ui->morphFactorSlider->maximum() - ui->morphFactorSlider->minimum());
```suggestion
    const auto factor = static_cast<float>(value) / (ui->morphFactorSlider->maximum() - ui->morphFactorSlider->minimum());
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/mainwindow.hpp
> +    Ui::MainWindow *ui;
Сырые указатели -> верный путь к утечкам памяти.

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/mainwindow.cpp
> +    delete ui;
А colorDialog кто удалит?

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cube.cpp
> +void Cube::initialize(size_t steps,
```suggestion
void Cube::initialize(const size_t steps,
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cube.cpp
> +void Cube::setEdgeColor(const QColor& color, int face)
```suggestion
void Cube::setEdgeColor(const QColor& color, const int face)
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cube.cpp
> +QColor Cube::getFaceColor(int face)
```suggestion
QColor Cube::getFaceColor(const int face)
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cube.cpp
> +QColor Cube::getEdgeColor(int face)
```suggestion
QColor Cube::getEdgeColor(const int face)
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cube.cpp
> +void Cube::setFaceColor(const QColor& color, int face)
```suggestion
void Cube::setFaceColor(const QColor& color, const int face)
```

2021-03-20 18:57 UTC, sadads1337 commented on src/Biryuchkov/Problem_2/cubewidget.cpp
> +    pCube_.reset(new Cube(
через `operator=` или `std::swap`

2021-03-21 08:11 UTC, biryuc commented on src/Biryuchkov/Problem_2/CMakeLists.txt
> +find_package(OpenGL REQUIRED)
Видимо нет, без этого не работает

2021-03-21 10:35 UTC, biryuc commented on src/Biryuchkov/Problem_2/cubewidget.cpp
> +void CubeWidget::setFaceMode()
Мне так удобнее разделить Mode

2021-04-04 04:58 UTC, sadads1337 approved these changes
Поправил часть проблем. Но код сильно переусложнен.

2021-04-04 04:58 UTC, sadads1337 commented on src/Biryuchkov/Task2/cube.hpp
> +  ~Cube() override = default;
Тут и базовом классе был потерян виртуальный деструктор.

2021-04-04 04:58 UTC, sadads1337 commented on src/Biryuchkov/Task2/cubewidget.hpp
> +  inline static const QColor initFaceColor = Qt::GlobalColor::lightGray;
странная конструкция в целом :)

2021-04-04 04:58 UTC, sadads1337 commented on src/Biryuchkov/Task2/rectflatgridsurface.cpp
> +  auto copy = *this;
Ваш класс держит gl context (т.к. замечание не было поправлено). Поэтому копия опасная операция, более того с 4+ контекстом это просто не будет работать

2021-04-04 04:59 UTC, merged

2021-04-10 14:10 UTC, sadads1337 commented on src/Biryuchkov/Task2/mainwindow.hpp
> +  Ui::MainWindow *ui = nullptr;
Тут остались сырые указатели, нужно не забыть поправить в следующей задаче