Task 2
sadads1337/fit-gl pull request #30
Opened 2021-03-18 04:04 UTC by oystop

Maybe it would be nice to create separate class for the object, hmm

2021-03-20 18:32 UTC, sadads1337 requested changes

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +        glVertexAttribPointer(posAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(VertexData), 0);
Лучше звать аналогичные методы у `program_` https://doc.qt.io/qt-5/qopenglshaderprogram.html#setAttributeArray

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +        glDisableVertexAttribArray(posAttr_);
И тут лучше звать соответствующий метод `program_`

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/main.cpp
> +      auto window = new CommonWidget();
Тут будет утечка памяти: `new` без `delete`

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/Shaders/vertex_shader.vs
> +   float x = posAttr.x;
Ой, а зачем так сложно то

Эквивалентный код:
```
void main() {
	vec3 r = posAttr.xyz;
	vec3 r_n = normalize(r);
	vec3 morphed_r = u_morph_param * r + (1 - u_morph_param) * r_n;
	vec4 morphed_poss = vec4(morphed_r.xyz, 1.0);
	gl_Position = u_projection_matrix * u_view_matrix * morphed_poss;
}
```

P.s: можно не править, а только ознакомиться :)

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.h
> +          float morph_param;
До первого "касания" слайдера, ваш `morph_param` содержит мусор, а значит гарантий на рисование кубика нет.
Задайте значение по-умолчанию.

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.h
> +          QBasicTimer timer;
Я бы оставил что-то одно: либо `timer`, либо `frame_`

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.h
> +        VertexData(){ }
Утверждается, что для эквивалентного поведения достаточно написать
```
struct V
{
  vec3 pos;
}
```

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +         emit color_change(color);
сигналы `color_change` и `morph_param_change` не реализованы(и не используются)

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +void MainWindow::initCube(float width, int N) {
```suggestion
void MainWindow::initCube(const float width, const int N) {
```

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +        auto step = width / float(N - 1);
`N == 1` не обработано :)

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +        auto aspect = w / (double)h;
```suggestion
        const auto aspect = w / static_cast<double>(h);
```

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +void MainWindow::resizeGL(int w, int h){
```suggestion
void MainWindow::resizeGL(const int w, const int h){
```

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +#define refreshRate 59
```suggestion
constexpr auto refreshRate  = 59;
```

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/CommonWidget.cpp
> +        auto * const Mwindow = owner<fgl::MainWindow *>(new fgl::MainWindow);
Вы же мне сможете объяснить, почему вы тут можете безнаказано писать `new`, и не реализовывать деструктор?)

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.cpp
> +#include <iostream>
Лишнее изменение?)

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/CommonWidget.cpp
> +    template<typename T, typename = std::enable_if_t<std::is_pointer<T>::value>>
А где же `#include<type_traits>` ?

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +        QVector<VertexData> vertexes;
- Я бы использовал `std::vector`, его поведение более ожидаемое.
- Перед вызовом циклов я бы посчитал количество вершин и сделал `reserve(N)`
- Вместо `push_back/append` я бы использовал `emplace_back`, чтобы избежать лишних копирований.

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.cpp
> +        QVector<GLuint> indexes;
И тут аналогично комментарию выше.

2021-03-20 18:32 UTC, sadads1337 commented on src/ostapchenko/task2/CommonWidget.cpp
> +        auto * const color = owner<QColorDialog *>(new QColorDialog);
`QColorDialog` - это диалоговое окно, не стоит его засовывать в `layout`. Как только вы нажмете "ok" или "cancel", он пропадет)

Чтобы починить это поведение, необходимо передать `QColorDialog::ColorDialogOption` https://doc.qt.io/qt-5/qcolordialog.html#ColorDialogOption-enum

2021-03-22 08:15 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +        glVertexAttribPointer(posAttr_, 3, GL_FLOAT, GL_FALSE, sizeof(VertexData), 0);
исправлено

2021-03-22 08:15 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +        glDisableVertexAttribArray(posAttr_);
исправлено

2021-03-22 08:15 UTC, oystop commented on src/ostapchenko/task2/main.cpp
> +      auto window = new CommonWidget();
исправлено

2021-03-22 08:15 UTC, oystop commented on src/ostapchenko/task2/MainWindow.h
> +          float morph_param;
исправлено

2021-03-22 10:12 UTC, oystop commented on src/ostapchenko/task2/CommonWidget.cpp
> +        auto * const color = owner<QColorDialog *>(new QColorDialog);
исправила

2021-03-22 10:44 UTC, oystop commented on src/ostapchenko/task2/CommonWidget.cpp
> +    template<typename T, typename = std::enable_if_t<std::is_pointer<T>::value>>
исправлено

2021-03-22 10:44 UTC, oystop commented on src/ostapchenko/task2/MainWindow.h
> +        VertexData(){ }
исправлено

2021-03-22 10:45 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +void MainWindow::initCube(float width, int N) {
+

2021-03-22 10:47 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +        auto aspect = w / (double)h;
+

2021-03-22 10:47 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +void MainWindow::resizeGL(int w, int h){
+

2021-03-22 10:47 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +#define refreshRate 59
+

2021-03-23 07:04 UTC, oystop commented on src/ostapchenko/task2/MainWindow.h
> +        VertexData(){ }
Без "конструктора" сложно инициализировать, поэтому оставила VertexData(QVector3D p) : position(p) {}


Так нравится!

2021-03-28 16:19 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +        QVector<VertexData> vertexes;
исправлено

2021-03-28 16:20 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +         emit color_change(color);
+

2021-03-28 16:21 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +        auto step = width / float(N - 1);
обработано

2021-03-28 16:22 UTC, oystop commented on src/ostapchenko/task2/MainWindow.cpp
> +        QVector<GLuint> indexes;
+

2021-04-04 06:04 UTC, sadads1337 commented on src/ostapchenko/task2/MainWindow.h
> +        VertexData(){ }
Ну вам то нравится, а эксперты по С++ (не я) говорят, что так делать не нужно :)

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c45-dont-define-a-default-constructor-that-only-initializes-data-members-use-in-class-member-initializers-instead

2021-04-04 06:11 UTC, sadads1337 approved these changes

2021-04-04 06:14 UTC, merged