Feature sayfudinova task 2
sadads1337/fit-gl pull request #33
Opened 2021-03-20 10:41 UTC by gergler

2021-03-20 19:02 UTC, sadads1337 requested changes

2021-03-20 19:02 UTC, sadads1337 commented on src/Base/GLWindow.hpp
> -
Лишние изменения

2021-03-20 19:02 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  time_ = end - start;
`time_`, `start`, `end` лишние. Просто передайте `std::chrono::system_clock::now()` в шейдер )

https://en.cppreference.com/w/cpp/chrono/time_point/time_since_epoch

2021-03-20 19:02 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +constexpr std::array<QVector3D, 194> vertices = {
Функцию генератор написать не решились?)

2021-03-24 18:44 UTC, gergler commented on src/sayfudinova/task2/CubeWindow.cpp
> +  time_ = end - start;
как-то кручу-верчу, но не получается вывести время таким способом
(std::chrono::duration<float>(std::chrono::duration_cast<std::chrono::seconds>((std::chrono::system_clock::now()).time_since_epoch())).count())

2021-03-25 03:42 UTC, gergler commented on src/sayfudinova/task2/CubeWindow.cpp
> +constexpr std::array<QVector3D, 194> vertices = {
добавила в новом коммите

2021-03-27 08:05 UTC, closed without merging