Kononov Task1
sadads1337/fit-gl pull request #4
Opened 2021-02-15 07:08 UTC by kononovarseniy

A short description of my solution is in the `src/Kononov/README.md` file.

I also added -llvmlibc-* check to the `.clang-tidy` to remove invalid warnings.

2021-02-15 15:22 UTC, sadads1337 requested changes

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Common/Camera.hpp
> +  [[nodiscard]] float getX() const;
можно `noexcept` и ниже на `get` методы

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Common/Camera.cpp
> +  QOpenGLContext::currentContext()->functions()->glViewport(x, y, w, h);
а если `context == nullptr`?) такое может случится, если не был вызван `make_current` или он завершился с ошибкой.

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Common/Camera.cpp
> +  m_projection.perspective(fov / ratio, ratio, near, far);
`ratio == 0`?

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Common/Camera.cpp
> +void Viewport::setX(float x) { m_x = x; }
`const float` и ниже

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Common/DirectionInputController.cpp
> +  m_yaw -= (float)diff.x() * m_sensitivity;
с cast -> static_cast

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Common/MotionInputController.hpp
> +  const std::shared_ptr<DirectionInputController> &getDirectionSource() const;
ссылка на shared_ptr странная штука :) Почему бы не вернуть просто shared_ptr или обычную ссылку на разыменований объект?

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/FirstRenderable.cpp
> +  // NOLINTNEXTLINE(cppcoreguidelines-owning-memory)
Подумайте, как сделать это без ручного вызова delete :)

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/main.cpp
> +static const int GL_VERSION_MAJOR = 3;
А почему не просто `constexpr`?)

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/MainWindow.cpp
> +constexpr std::array<GLfloat, 192U> modelVertices = {
можно прятать в анонимный namespace

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/MainWindow.cpp
> +static const float PERSPECTIVE_FOV = 60.0F;
просто constexpr?)

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/MainWindow.cpp
> +      (char *)modelVertices.data(), modelVertices.size() * sizeof(GLfloat),
c cast -> reinterpret_cast

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/MainWindow.cpp
> +  const auto ratio = (float)width() / (float)height();
static_cast

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Common/ShaderProgram.hpp
> +class ShaderProgram {
А где же ваш virtual деструктор?)

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/shaders/first.fs
> +    gl_FragColor = vec4(ambient_light + diffuse_light + specular_light, 1) * texture(diffuse_map, frag_uv);
Вы просите 330 версию шейдера, но используете deprecated `gl_FragColor`
Это скорее всего вообще не заработает на большинстве платформ, надо что-то вроде
```
out vec4 color;

...

void main() {
  ...
  color = ...;
}
```

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/FirstShader.hpp
> +  GLint m_diffuse_map{};
тут и без {} будет zero-init

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/FirstShader.cpp
> +  m_vertex_position_attr = shader->attributeLocation("vertex_position");
initializer list можно использовать

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/FirstRenderable.cpp
> +                                   const char *vbo_data, int vbo_size,
А почему бы не принимать `std::vector<Vertex> &&`, `std::vector<size_t> &&` вершин и индексов?)

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/MainWindow.cpp
> +    -1.0F, -1.0F, 1.0F, 0, 0, 1, 0.0F, 0.0F,  // v0
Почему не завести plain структуру с полями. Пример:
```
struct Vertex
{
 vec3 pos;
 vec3 col;
 vec3 norm;
 vec2 uv;
}
```

2021-02-15 15:22 UTC, sadads1337 commented on src/Kononov/Task1/MainWindow.cpp
> +    -1.0F, -1.0F, 1.0F, 0, 0, 1, 0.0F, 0.0F,  // v0
stride = sizeof(Vertex);
offset = смещение до поля, можно считать такой магией:
```
template <typename C, typename M>
inline ptrdiff_t member_offset(M C::* member) noexcept
{
	constexpr const std::byte *null_ptr = nullptr;
	return reinterpret_cast<const std::byte *>(
		&(static_cast<const C *>(nullptr)->*member)) - null_ptr;
}

...

member_offset(Vertex::pos);
```

2021-02-16 05:06 UTC, kononovarseniy commented on src/Kononov/Common/Camera.cpp
> +void Viewport::setX(float x) { m_x = x; }
Не понимаю о чем вы.

2021-02-16 05:31 UTC, kononovarseniy commented on src/Kononov/Common/Camera.cpp
> +  QOpenGLContext::currentContext()->functions()->glViewport(x, y, w, h);
Добавил вспомогательные функции GLUtil::require* для получения контекста и функций.

2021-02-16 05:37 UTC, kononovarseniy commented on src/Kononov/Common/Camera.cpp
> +  m_projection.perspective(fov / ratio, ratio, near, far);
Добавил проверку на std::isnormal() для всех аргументов. Случаи когда углы обзора слишком большие, плоскости отсечения в неправильном порядке и т.д. намеренно не рассматриваю, поскольку считаю что вызывающий код должен сам следить за корректностью этих параметров.

2021-02-16 05:41 UTC, kononovarseniy commented on src/Kononov/Common/DirectionInputController.cpp
> +  m_yaw -= (float)diff.x() * m_sensitivity;
Исправил

2021-02-16 05:42 UTC, kononovarseniy commented on src/Kononov/Task1/MainWindow.cpp
> +      (char *)modelVertices.data(), modelVertices.size() * sizeof(GLfloat),
Исправил

2021-02-16 05:44 UTC, kononovarseniy commented on src/Kononov/Task1/FirstShader.hpp
> +  GLint m_diffuse_map{};
Исправил

2021-02-16 05:49 UTC, kononovarseniy commented on src/Kononov/Task1/FirstShader.cpp
> +  m_vertex_position_attr = shader->attributeLocation("vertex_position");
Хотелось бы, но этому мешает нетривиальная инициализация шейдера (атрибуты появляются только после вызовов addShaderFromSourceFile() и link()). Или это как-то можно обойти?

2021-02-16 06:37 UTC, kononovarseniy commented on src/Kononov/Common/MotionInputController.hpp
> +  const std::shared_ptr<DirectionInputController> &getDirectionSource() const;
Объект почти всегда имеет несколько ссылок на него => Поле m_object должно хранить shared_ptr.

Возвращать ссылку на разыменованный объект нельзя поскольку тогда нельзя будет нормально взять указатель на объект (например чтобы передать его в другой контроллер).

Ссылка на shared_ptr используется чтобы избежать лишнего копирования при возврате значения.

2021-02-16 07:20 UTC, kononovarseniy commented on src/Kononov/Task1/main.cpp
> +static const int GL_VERSION_MAJOR = 3;
Исправил

2021-02-16 08:12 UTC, kononovarseniy commented on src/Kononov/Common/ShaderProgram.hpp
> +class ShaderProgram {
Совсем забыл про него

2021-02-16 08:19 UTC, kononovarseniy commented on src/Kononov/Task1/FirstRenderable.cpp
> +                                   const char *vbo_data, int vbo_size,
Я пытался сделать класс универсально оборачивающий VBO и IBO без привязки к определенной структуре вершины и типу индексов. Чтобы можно было создать объекты у которых в вершинах, например, только координаты и цвета.
Можно конечно попробовать сделать template, но структура вершины тесно связанна с шейдером, а значит классы шейдеров тоже надо сделать подругому.

2021-02-16 19:54 UTC, sadads1337 commented on src/Kononov/Common/MotionInputController.hpp
> +  const std::shared_ptr<DirectionInputController> &getDirectionSource() const;
Копирования не будет из-за rvo:)

2021-02-17 03:24 UTC, kononovarseniy commented on src/Kononov/Common/MotionInputController.hpp
> +  const std::shared_ptr<DirectionInputController> &getDirectionSource() const;
Извините, но я считаю что RVO в данном случае не будет применено.

Поскольку RVO обычно применяетс когда функция *создаёт* новый объект. Но в данном случае метод возвращает уже существующий объект.

Поэтому, если возвращать без использования ссылки:
```cpp
auto a = controller.getObject(); // Происходит одно копирование
std::cout << controller.getObject()->getЧтонибудь(); // Тоже копирование
```
Однако с использованием ссылки во втором случае копирования не происходит.

Конечно, копирование shared_ptr не самая дорогая операция, и во многих случаях используется код как в первом случае. Но ценой всего одного символа `&` я получаю код выполняющий минимальное количество копирований независимо от реализации компилятором необязательного RVO.

Все вышесказанное я проверил на этом коде, в том числе компилируя с флагом `-O3`
```cpp
#include <iostream>

class Foo {
public:
    int m_value;

    explicit Foo(int value) :
            m_value(value) {
        std::cout << "Ctor " << m_value << std::endl;
    }

    Foo(const Foo &other) :
            m_value(other.m_value) {
        std::cout << "Copy ctor " << m_value << std::endl;
    }
};

Foo global(42);

Foo getGlobal() {
    return global;
}

Foo &getGlobalRef() {
    return global;
}

Foo makeNew() {
    return Foo(121);
}

int main() {
    Foo first(1);
    Foo second = first;      // Copy  (1)
    Foo third = getGlobal(); // Copy  (42)
    Foo fourth = makeNew();  // RVO
    std::cout << getGlobal().m_value << std::endl; // Copy (42)
    std::cout << getGlobalRef().m_value << std::endl; // Without copy

    std::cout << first.m_value << " " << second.m_value << " " << third.m_value << " " << fourth.m_value << std::endl;
    return 0;
}

```

2021-02-17 21:00 UTC, sadads1337 commented on src/Kononov/Common/Camera.cpp
> +void Viewport::setX(float x) { m_x = x; }
в реализации методов можно и нужно писать `const float x` для параметров, если они имеют const-семантику :)

2021-02-17 21:07 UTC, sadads1337 approved these changes

2021-02-17 21:07 UTC, sadads1337 commented on src/Kononov/Task1/FirstShader.cpp
> +  m_vertex_position_attr = shader->attributeLocation("vertex_position");
Да, согласен. Насчет обойти: "здоровых идей в голову не приходит"

2021-02-17 21:07 UTC, sadads1337 commented on src/Kononov/Common/GLUtil.hpp
> +  static QOpenGLContext *requireContext();
Я бы сделал свободные функции, а то какой-то JAVA-way :) Но это так вкусовщина

2021-02-17 21:10 UTC, sadads1337 commented on src/Kononov/Common/MotionInputController.hpp
> +  const std::shared_ptr<DirectionInputController> &getDirectionSource() const;
Да не за что извиняться, я тоже могу быть не прав, это же C++ :)
Вы правы, не NRVO не RVO не будут применены, еще раз прочитал про copy-ellision 
Копирование shared_ptr - не дешевая операция, хотя это, конечно, как посмотреть...
Можно разводить демагогию о семантике и потенциальных висячих указателях, но в целом, ваша позиция аргументирована и я готов ее принять!

2021-02-17 21:12 UTC, sadads1337 commented
Меня более чем устраивает такое решение, к тому же вы сделали больше чем было нужно. Апрув и 5 за задачу.

2021-02-17 21:14 UTC, sadads1337 commented
Остальные задачи вам тоже могут показаться "скучными", поэтому предлагаю вам подумать над интересной вам темой в области графики, разбить ее на несколько осмысленных конечных шагов (подзадач), и попробовать реализовать их в рамках лабораторных работ.

2021-02-21 12:52 UTC, merged