Feature ostapchenko task 3
sadads1337/fit-gl pull request #48
Opened 2021-04-09 16:17 UTC by oystop

Task 3

2021-04-25 04:37 UTC, sadads1337 requested changes
Нужно рисовать треугольники.

2021-04-25 04:37 UTC, sadads1337 commented on src/ostapchenko/task3/MainWindow.cpp
> +          context()->functions()->glDrawElements(GL_LINES, indexBuffer.size(),
Не, ну я конечно спрошу. А чего вы ожидаете увидеть освещая линии?))))))

2021-04-26 05:28 UTC, oystop commented on src/ostapchenko/task3/MainWindow.cpp
> +          context()->functions()->glDrawElements(GL_LINES, indexBuffer.size(),
исправила:))

2021-05-17 01:42 UTC, sadads1337 approved these changes

2021-05-17 01:58 UTC, merged