sayfudinova-task-2
sadads1337/fit-gl pull request #49
Opened 2021-04-10 09:35 UTC by gergler

2021-04-10 16:04 UTC, sadads1337 requested changes

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/Shaders/quad.vs
> +    float x = posAttr.x;
Уже раз в 5 вижу этот код, даж названия одинаковые :)))) Хочу чтобы вы не просто копипастили, а разбирались (и, возможно, читали комментарии к чужим работам)

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/Shaders/quad.vs
> +uniform highp vec4 coord;
`uniform coord` не используется, зачем его передавать?

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/Shaders/quad.vs
> +attribute highp vec4 posAttr;
Зачет тип атрибута `vec4`, достаточно же vec3

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/Shaders/quad.vs
> +    float x = posAttr.x;
Учитывая замечания выше, есть "решение в 1 строчку" :) Прочитайте и разберитесь в нем.

```
#version 120

attribute highp vec3 posAttr;
uniform highp mat4 matrix;
uniform float time;

vec3 param(float time){
    float value = (sin(time) + 1.) / 2.;
    return vec3(value, value, value);
}

void main() {
    vec3 morphed_vertex = mix(posAttr.xyz, normalize(posAttr.xyz), param(time));
    gl_Position = matrix * vec4(morphed_vertex, 1.);
}
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.h
> +  void mousePressEvent(QMouseEvent *e) override;
Давайте для единообразия (и ниже)
```suggestion
  void mousePressEvent(QMouseEvent *event) override;
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  glDrawElements(GL_LINES, ibo.size(), GL_UNSIGNED_INT, nullptr);
Хорошая практика - делать `bind` для `VBO` + `IBO` перед каждым вызовом `glDrawElements`

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  VertexData(QVector3D p) :
Конструкторы лишние
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c45-dont-define-a-default-constructor-that-only-initializes-data-members-use-in-class-member-initializers-instead

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  QVector<VertexData> vertices;
Удобнее было бы использовать `std::vector<VertexData>` + `emplace_back`

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  QVector<VertexData> vertices;
И для индексов тоже :)

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  float halfWidth = width / 2;
```suggestion
  auto halfWidth = width / 2.f;
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  float step = width / float(N - 1);
```suggestion
  auto step = width / static_cast<float>(N) - 1.f;
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  float step = width / float(N - 1);
Не обработан случай `N == 1`

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  start = std::chrono::system_clock::now();
Давайте поле класса старт тоже напишем с суффиксом `_`, как и другие поля (для единообразия)
```suggestion
  start_ = std::chrono::system_clock::now();
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  QVector3D position;
Обратите внимание, что задаете в cpp коде как `vec3`, а в шейдере читаете атрибут как `vec4`, это может привести к проблемам :)

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +        indices.append(i + j + k + N);
индексы в циклах целые (int), а элементы в массивы `unsigned`, нужно привести типы (`static_cast`) или поправить в циклах.

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +    QColor color = QColorDialog::getColor();
```suggestion
    const auto color = QColorDialog::getColor();
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +    changeColor = QVector4D(color.red() / 255.0, color.green() / 255.0,
```suggestion
    changeColor_ = QVector4D(color.red() / 255.0, color.green() / 255.0,
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  mousePressPosition = QVector2D(e->localPos());
```suggestion
  mousePressPosition_ = QVector2D(e->localPos());
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.cpp
> +  rotationAxis = QVector3D(diff.y(), diff.x(), 0.0).normalized();
```suggestion
  rotationAxis_ = QVector3D(diff.y(), diff.x(), 0.0).normalized();
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.h
> +  QOpenGLBuffer vbo;
```suggestion
  QOpenGLBuffer vbo_;
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.h
> +  QOpenGLBuffer ibo{QOpenGLBuffer::Type::IndexBuffer};
```suggestion
  QOpenGLBuffer ibo_{QOpenGLBuffer::Type::IndexBuffer};
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.h
> +  QVector4D changeColor{0.5, 0.0, 0.6, 1};
```suggestion
  QVector4D changeColor_{0.5, 0.0, 0.6, 1};
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.h
> +  std::chrono::time_point<std::chrono::system_clock> start;
```suggestion
  std::chrono::time_point<std::chrono::system_clock> start_;
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.h
> +  QVector2D mousePressPosition{0., 0.};
```suggestion
  QVector2D mousePressPosition_{0., 0.};
```

2021-04-10 16:04 UTC, sadads1337 commented on src/sayfudinova/task2/CubeWindow.h
> +  QVector3D rotationAxis = QVector3D(0.0, 1.0, 0.0).normalized();
```suggestion
  QVector3D rotationAxis_ = QVector3D(0.0, 1.0, 0.0).normalized();
```

2021-04-11 05:58 UTC, gergler commented
Исправила ошибки

2021-04-25 04:46 UTC, merged