task1
sadads1337/fit-gl pull request #5
Opened 2021-02-19 13:52 UTC by Lexxsage

Task 1 cube done

2021-02-19 21:01 UTC, sadads1337 commented
Остальное проще обсудить устно на паре.

2021-02-19 21:04 UTC, sadads1337 requested changes

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/CMakeLists.txt
> -set(LESSON1_SRCS
А зачем вы пример lesson1 удаляете из репозитория?) переместите ваш код в `<project-root>/src/<surname>/task1`

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/CMakeLists.txt
> +    if(ANDROID)
Вы собирали под андройд, тогда где же ваш `gradle` билдскрипт?)

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/CMakeLists.txt
> +if(${QT_VERSION_MAJOR} GREATER_EQUAL 6)
Давайте не будем тащить qt 6 :)

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/CMakeLists.txt.user
> +<?xml version="1.0" encoding="UTF-8"?>
Лишний файл, относящийся к вашей IDE

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/CubeObject.h
> +    CubeObject() = delete;
Лишнее, как только вы объявили пользовательский конструктор (ниже), конструктор по умолчанию удалился автоматически.

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/CubeObject.h
> +    explicit CubeObject(GLfloat edgeLen, GLuint verticesCnt) : edgeLen_(edgeLen) {
`explicit` лишний, код в заголовочнике лучше не писать, вы потенциально замедляете компиляцию

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/cubeedges.h
> +#ifndef CUBEEDGES_H
Это C штука, не смотря на то, что `#pragma once` до сих пор не стандартизован, он есть в любом компиляторе. Лучше использовать эту директиву.

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/plainobject3d.cpp
> +void PlainObject3D::render(QOpenGLShaderProgram* program)
А зачем вам указатель?) Кажется, достаточно просто ссылки на `QOpenGLShaderProgram`

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/plainobject3d.cpp
> +    auto m_posAttr = program->attributeLocation("posAttr");
обычно prefix `m_*` используется для полей структур/классов, тут у вас обычная локальная переменная.

еще почему не `const auto` ?)

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/mymainwindow.h
> +class MyMainWindow : public QWindow, protected QOpenGLFunctions
А почему не наследоваться от `Base/GLWindow.hpp` ? Зачем копипастить код :)

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/mymainwindow.h
> +    QOpenGLContext *m_context = nullptr;
Сырые указатели без веских причин использования - путь к утечкам памяти, используйте `RAII` и умные указатели (`unique_ptr`, `shared_ptr`). К тому же вам не придется писать деструкторы :)

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/mymainwindow.h
> +    explicit MyMainWindow(QWindow *parent = nullptr);
Если вы действительно реализуете деструктор, то следуйте правилу 5: https://www.modernescpp.com/index.php/c-core-guidelines-constructors-assignments-and-desctructors

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/cubewindow.h
> +    QOpenGLShaderProgram *m_program = nullptr;
Сырой указатель

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/cubewindow.h
> +    QOpenGLShaderProgram *m_program = nullptr;
И ниже

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/cubewindow.cpp
> +    cube.render(m_program);
Я бы сделал интерфейс `IRenderable` с виртуальным методом `render`. И в этом классе хранил список из указателей на объекты, реализующие этот интерфейс.

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/cubeedges.cpp
> +    for (unsigned i = 0; i < 8 * dim; i += dim){                           /* frirst 8 */
Выглядит, конечно, слегка "упорото", я бы просто захардкодил вершины и индексы :)

2021-02-19 21:04 UTC, sadads1337 commented on src/Lesson1/cubeedges.cpp
> +void CubeEdges::setVertices()
В качестве упражнения: подумайте как с помощью фрагментного шейдера можно нарисовать вершины без вызовов GL_LINES :)

2021-02-20 04:48 UTC, Lexxsage commented on src/Lesson1/CubeObject.h
> +    explicit CubeObject(GLfloat edgeLen, GLuint verticesCnt) : edgeLen_(edgeLen) {
Замедляет компиляцию, но ведь будет быстрее в рантайме - тут же смотря какие у нас цели, а цели минимизировать время компиляции  вроде не было
Да и это всего лишь присваивание значения переменной

2021-02-22 19:05 UTC, sadads1337 commented on src/Lesson1/mymainwindow.h
> +class MyMainWindow : public QWindow, protected QOpenGLFunctions
Копипасту не поправили )

2021-02-27 13:05 UTC, sadads1337 approved these changes

2021-02-27 13:05 UTC, merged