Feature moseykov task3
sadads1337/fit-gl pull request #57
Opened 2021-04-19 00:22 UTC by MoseykovIgnat

2021-04-25 05:59 UTC, sadads1337 requested changes
Перед своими правка не забудьте подтянуть up-stream ветку

2021-04-25 05:59 UTC, sadads1337 commented on src/Moseykov/task3/MyWidget.h
> +#ifndef FIT_GL_MYWIDGET_H
Давайте использовать `#pragma once`

2021-04-25 05:59 UTC, sadads1337 commented on src/Moseykov/task3/Shaders/square.fs
> +    //For GURO
Давайте комментированный код не будем оставлять.
Проще вынести в 2 разных шейдера 2 модели.
Либо параметризовать шейдер `uniform`'ом

2021-04-25 05:59 UTC, sadads1337 commented on src/Moseykov/task3/SquareWindow.cpp
> +      glDrawElements(GL_LINES, indexBuffer.size(), GL_UNSIGNED_INT, nullptr);
Как вы собираетесь разницу между Гуро и Фонгом увидеть на линиях? Давайте рисовать треугольники

2021-04-26 07:20 UTC, MoseykovIgnat commented on src/Moseykov/task3/SquareWindow.cpp
> +      glDrawElements(GL_LINES, indexBuffer.size(), GL_UNSIGNED_INT, nullptr);
Исправил

2021-04-26 07:20 UTC, MoseykovIgnat commented on src/Moseykov/task3/Shaders/square.fs
> +    //For GURO
Исправил

2021-04-26 07:20 UTC, MoseykovIgnat commented on src/Moseykov/task3/MyWidget.h
> +#ifndef FIT_GL_MYWIDGET_H
Исправил

2021-05-17 02:09 UTC, sadads1337 commented
А нормали для морфированной сферы почему не пересчитываются? (из-за этого освещение не правильное)

2021-05-17 02:12 UTC, merged

2021-05-17 02:12 UTC, MoseykovIgnat commented
Выполнял задачу только для кубов, морфинг остался со второй задачи.
Если нужно - могу разобраться и перечитывать нормали, но я думал, что для кубов достаточно