Feature ostapchenko task 1
sadads1337/fit-gl pull request #6
Opened 2021-02-21 15:12 UTC by oystop

The program supports changing the axis of rotation using the mouse

2021-02-22 19:00 UTC, sadads1337 requested changes

2021-02-22 19:00 UTC, sadads1337 commented on CMakeLists.txt
> +
лишнее изменение

2021-02-22 19:00 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.cpp
> +        glClear(GL_COLOR_BUFFER_BIT);
А почему вы не очищаете буфер глубины?

2021-02-22 19:00 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.cpp
> +        glGenBuffers(1, &vbo);
Можно так оставить, можно использовать https://doc.qt.io/qt-5/qopenglbuffer.html

2021-02-22 19:00 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.cpp
> +        QVector2D diff = QVector2D(e->localPos()) - mousePressPosition;
А что будет, если ReleaseEvent придет раньше, чем был первый PressEvent?)

посмотрите на инициализацию поля mousePressPosition

2021-02-22 19:00 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.cpp
> +        program_->removeAllShaders();
Деструктор шейдерной программы разве сам не освободит за собой ресуры?)

2021-02-22 19:00 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.h
> +        ~SquareWindow();
Есть такие правила, называются "правило 0, 3, 5", погуглите )

2021-02-22 19:00 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.h
> +    protected:
Не хватает диалогового окна для смены цвета кубика, посмотрите, например, на QColorDialog

2021-02-22 19:02 UTC, sadads1337 commented
Поправьте конфликт в src/CMakeLists.txt.
Для этого выполните команды
```
git checkout master;
git pull;
git checkout <your-branch-name>;
git rebase -i master;
(разрешите конфликты);
git commit; git rebase --continue;
git push -f;
```

2021-02-23 08:10 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.cpp
> +    VertexData vertices[] = {
А почему снижу std::array, а тут нет?)

2021-02-23 08:11 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.h
> +        ~SquareWindow();
https://en.cppreference.com/w/cpp/language/rule_of_three

2021-02-25 10:32 UTC, oystop commented on src/ostapchenko/task1/SquareWindow.cpp
> +        QVector2D diff = QVector2D(e->localPos()) - mousePressPosition;
Он будет вращаться относительно оси (0, 0, 0)

2021-02-25 10:32 UTC, oystop commented on src/ostapchenko/task1/SquareWindow.cpp
> +        program_->removeAllShaders();
Освободит :)

2021-02-27 12:34 UTC, sadads1337 approved these changes

2021-02-27 12:34 UTC, sadads1337 commented on src/ostapchenko/task1/SquareWindow.cpp
> +            QColor color = QColorDialog::getColor();
```suggestion
            const auto color = QColorDialog::getColor();
```
https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

2021-02-27 12:50 UTC, sadads1337 commented
@oystop поправил маленькие замечания. В следующий раз, отписывайтесь в комментариях, что замечания поправлено.

2021-02-27 12:51 UTC, merged