Feature ostapchenko task 4
sadads1337/fit-gl pull request #62
Opened 2021-04-24 05:52 UTC by oystop

Task 4!

2021-04-25 06:23 UTC, sadads1337 requested changes

2021-04-25 06:23 UTC, sadads1337 commented on src/ostapchenko/task4/CommonWidget.h
> +class CommonWidget : public QWidget {
Весь `CommonWidget` можно смело выкинуть, нам не нужны: ни морфиг, ни смена цвета

2021-04-25 06:23 UTC, sadads1337 commented on src/ostapchenko/task4/MainWindow.h
> +  VertexData(){ }
Конструкторы лишние

2021-04-25 06:23 UTC, sadads1337 commented on src/ostapchenko/task4/MainWindow.h
> +  QOpenGLTexture *texture = nullptr;
Raw-pointer'ы. Используйте умные указатели

2021-04-26 05:42 UTC, oystop commented on src/ostapchenko/task4/CommonWidget.h
> +class CommonWidget : public QWidget {
Исправлено

2021-04-26 05:42 UTC, oystop commented on src/ostapchenko/task4/MainWindow.h
> +  VertexData(){ }
Исправлено

2021-04-26 05:59 UTC, oystop commented on src/ostapchenko/task4/MainWindow.h
> +  QOpenGLTexture *texture = nullptr;
Исправлено

2021-05-17 01:39 UTC, sadads1337 approved these changes

2021-05-17 02:07 UTC, merged