Feature nikolaev task1
sadads1337/fit-gl pull request #8
Opened 2021-02-23 07:36 UTC by AndrewNikoala

First task done. Attempt 1

2021-02-23 08:06 UTC, sadads1337 requested changes

2021-02-23 08:06 UTC, sadads1337 commented on src/CMakeLists.txt
> +set(CMAKE_PREFIX_PATH "C:/Qt/5.15.2/mingw81_64")
Ваше локальное изменение, в общем коде его не должно быть. Иначе вы сломаете сборку всем остальным

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/CMakeLists.txt
> +        geometryengine.cpp geometryengine.h
Давайте как-нибудь согласованно именовать файлы, например, в `CamelCase.cpp`, а то выглядит, как "небрежная" копипаста

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/CMakeLists.txt
> +add_subdirectory(Task1)
Лишний файл, можно просто в CMake уровнем выше написать `add_subdirectory(Nikolaev/Task1)`

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/Controller/InputController.h
> +    std::unordered_set<int> pressedKeys;
У qt для таких целей есть что-то вроде `QFlags`, но можно не править

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/MainWindow.h
> +    std::shared_ptr<InputController> m_change_colors;
Зачем `shared_ptr` на `InputController`, кажется им владеет только `MainWindow `

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/MainWindow.h
> +    GeometryEngine *geometries = nullptr;
Сырой указатель - путь к утечкам памяти, используйте `unique_ptr`. Да и вообще, нужен ли тут указатель?

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/Shaders/triangle.fs
> +#version 120
У вас 2 копии одинаковых шейдеров

`fshader.glsl = triangle.fs`
`vshader.glsl = triangle.vs`

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/cube.pro
> +    mainwidget.cpp \
Названия файлов case-sensitive или нет?)

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/geometryengine.cpp
> +{
Зачем деструктор `GeometryEngine`? Ожидается, что деструктор полей типа `QOpenGLBuffer` корректно почистит данные за собой. https://doc.qt.io/qt-5/qopenglbuffer.html#dtor.QOpenGLBuffer

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/geometryengine.cpp
> +    // { coordinates(x, y, z) } ,{ normal vector (x, y, z) }, { color (r, g, b) }
Зачем вам вектор нормали? Вы не используете его в шейдере и коде

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/geometryengine.h
> +    virtual ~GeometryEngine();
`virtual ~GeometryEngine() = default`;

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/main.cpp
> +#ifndef QT_NO_OPENGL
Зачем обрабатывать этот случай?) Подразумеваем, что пользователь запустит на "правильной платформе"

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/textures.qrc
> +        <file>cube.png</file>
Зачем текстура, если вы ее не используете?

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/geometryengine.cpp
> +    size_t stride = sizeof(GLfloat) * 9;
```suggestion
    const auto stride = sizeof(GLfloat) * 9u;
```
Есть такое правило о экспертов с++, называется AAA - almost always auto. https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/MainWindow.cpp
> +    QVector2D diff = QVector2D(e->localPos()) - mousePressPosition;
Второй раз вижу этот код, надеюсь, что вы разобрались, что сделали :)

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/MainWindow.cpp
> +    QVector2D diff = QVector2D(e->localPos()) - mousePressPosition;
И вопрос такой, что будет, если вам "прилетит" событие `ReleaseEvent` раньше, чем `PressEvent`

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/MainWindow.cpp
> +    makeCurrent();
Лишний код, неправильный комментарий.

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/CMakeLists.txt
> +        cube.png
Текстур у вас нет, зачем добавляете эти файлы сюда, да и вообще в PR ?)

2021-02-23 08:06 UTC, sadads1337 commented on src/Nikolaev/Task1/MainWindow.cpp
> +MainWindow::~MainWindow()
Если вы таки решили писать деструктор, то следуйте `правилам 0, 3, 5` https://en.cppreference.com/w/cpp/language/rule_of_three

2021-02-23 08:35 UTC, AndrewNikoala commented on src/Nikolaev/Task1/MainWindow.cpp
> +    QVector2D diff = QVector2D(e->localPos()) - mousePressPosition;
Дак, это с официального примера qt cube. 
Нажали кнопку мыши (сохранили состояние), отпустили кнопку мыши. Посчитали разницу между этими двумя позициями.
Нашли ускорение кубика. 
В рендеринге завращали его

2021-02-23 08:41 UTC, AndrewNikoala commented on src/Nikolaev/Task1/MainWindow.cpp
> +    QVector2D diff = QVector2D(e->localPos()) - mousePressPosition;
По всей видимости, всё сломается. Так как mousePressPosition ещё не будет существовать.

2021-02-23 09:20 UTC, AndrewNikoala commented on src/Nikolaev/Task1/MainWindow.cpp
> +MainWindow::~MainWindow()
Cовсем его убрал. Использую умные указатели

2021-02-27 13:12 UTC, sadads1337 approved these changes

2021-02-27 13:12 UTC, sadads1337 commented on src/Nikolaev/Task1/GeometryEngine.cpp
> +    std::array<GLfloat, 216u> vertices = {
Почему бы не сохранить `vertices` в качестве поля класса и тут не модифицировать только цвет?

2021-02-27 13:12 UTC, sadads1337 commented on src/Nikolaev/Task1/GeometryEngine.cpp
> +    size_t stride = sizeof(GLfloat) * 9;
```suggestion
    const auto stride = sizeof(GLfloat) * 9;
```
https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

2021-02-27 13:12 UTC, sadads1337 commented on src/Nikolaev/Task1/GeometryEngine.cpp
> +    int vertexLocation = program->attributeLocation("a_position");
И тут 
```suggestion
    const auto vertexLocation = program->attributeLocation("a_position");
```

2021-02-27 13:12 UTC, sadads1337 commented on src/Nikolaev/Task1/GeometryEngine.cpp
> +    int vertexColor = program->attributeLocation("vertex_color");
```suggestion
    const auto vertexColor = program->attributeLocation("vertex_color");
```

2021-02-27 13:12 UTC, sadads1337 commented on src/Nikolaev/Task1/GeometryEngine.h
> +#ifndef FIT_GL_GEOMETRYENGINE_H_H
Хоть `#pragma once` и не стандартизирован, но присутствует в любом современном компиляторе, давайте использовать его. И в других хедерах тоже

2021-02-27 13:12 UTC, sadads1337 commented on src/Nikolaev/Task1/MainWindow.cpp
> +    QVector3D n = QVector3D(diff.y(), diff.x(), 0.0).normalized();
```suggestion
    const auto n = QVector3D(diff.y(), diff.x(), 0.0).normalized();
```

Пробегитесь по коду, поправьте все такие места :)

2021-02-27 13:12 UTC, sadads1337 commented on src/Nikolaev/Task1/MainWindow.cpp
> +    //glCullFace(GL_FRONT);
Закомментированный код, наверное, лучше не оставлять :)

2021-02-27 13:30 UTC, sadads1337 commented
@AndrewNikoala поправил ваш код, поребейзил его на мастер.

Если у вас есть локальные изменения сохраните их в отдельный коммит (или используйте `git stash`)
Затем обновите ветку, например: `git fetch; git reset --hard origin/feature-nikolaev-task1`

2021-02-28 07:36 UTC, merged