biryuchkov task 1
sadads1337/fit-gl pull request #9
Opened 2021-02-24 05:33 UTC by biryuc

2021-02-24 16:00 UTC, sadads1337 commented
Я конечно ради приличия спрошу, но почему ваше задания коммитит другой человек. @Lexxsage @biryuc

2021-02-24 16:07 UTC, sadads1337 requested changes

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/Task 1/TriangleWindow.cpp
> +TriangleWindow::~TriangleWindow(){
Деструктор лишний, следуйте правилам 3, 0, 5 https://en.cppreference.com/w/cpp/language/rule_of_three

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/Task 1/TriangleWindow.cpp
> +//void TriangleWindow::timerEvent(QTimerEvent *)
Закомментированный код нужно убрать

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/Task 1/TriangleWindow.cpp
> +  unsigned int vbo;
Почему не QOpenGLBuffer?

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/Task 1/TriangleWindow.hpp
> +class TriangleWindow final : public GLWindow {
Давайте давать согласованные имена, у вас явно не треугольник в коде.

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/Task 1/TriangleWindow.cpp
> +VertexData gvertices[] = {
Почему не std::array?

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/Task 1/shaders.qrc
> +        <file>Shaders/triangle.fs</file>
Имена шейдеров нужно тоже поправить

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/Task 1/TriangleWindow.cpp
> +  glClear(GL_COLOR_BUFFER_BIT);
А где же очищение DEPTH буфера?

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/Task 1/CMakeLists.txt
> +add_executable(lesson1 ${LESSON1_SRCS})
`lesson1` или все же `task1`?

2021-02-24 16:07 UTC, sadads1337 commented on src/biryuchkov/CMakeLists.txt
> +add_subdirectory(Task1)
Лишнее, можно писать `add_subdirectory(biryuchkov/task1)` в `CMakeLists.txt` уровнем выше

2021-02-24 16:08 UTC, sadads1337 commented
И еще, где смена цвета куба?

2021-02-25 08:47 UTC, biryuc commented on src/biryuchkov/Task 1/TriangleWindow.cpp
> +VertexData gvertices[] = {
Взял из примера Qt, с std :: array почему-то возникали ошибки при подборе правильных коэффициентов для куба.

2021-02-26 14:13 UTC, closed without merging